services:
  postgres:
    image: postgres:16
    container_name: fiber-postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=huuloc2026
      - POSTGRES_DB=fiber-api
    volumes:
      - fiber_postgres:/var/lib/postgresql/data
    networks:
      - fiber_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      timeout: 20s
      retries: 10

networks:
  fiber_network:

volumes:
  fiber_postgres:
